### ISSUE TITLE
Incorrect peer dependecy (commander)

### ISSUE THREAD

**Issue by panki** [Pop-Code/nestjs-console#58] opened 2019-11-28 10:13 UTC
Since nestjs uses commander ^4.0.1, installing nestjs-console leads to:

```bash
yarn add commander nestjs-console                                                                                                                                    ✹ ✭
yarn add v1.19.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning Pattern ["commander@^4.0.1"] is trying to unpack in the same destination "/Users/panki/Library/Caches/Yarn/v6/npm-commander-4.0.1-b67622721785993182e807f4883633e6401ba53c-integrity/node_modules/commander" as pattern ["commander@4.0.1"]. This could result in non-deterministic behavior, skipping.
[3/4] 🔗  Linking dependencies...
warning " > nestjs-console@1.2.0" has incorrect peer dependency "commander@^3.0.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 3 new dependencies.
info Direct dependencies
├─ commander@4.0.1
└─ nestjs-console@1.2.0
info All dependencies
├─ commander@4.0.1
├─ log-symbols@2.2.0
└─ nestjs-console@1.2.0
✨  Done in 3.26s.
```

**Comment by Rmannn** [comment] 2019-11-28 17:00
Hi, I didn't know nestjs was using commander.
It's a dependency that was introduced from the @nestjs/cli.

A v2 branch was created to start supporting commander 4 a few days ago.
The link between commander and nestjs-console was rewrite.

I need to rewrite some tests and we will be good to publish.

**Comment by panki** [comment] 2019-12-03 09:24
Super, thank you!

**Comment by Rmannn** [comment] 2020-01-01 03:04
Duplicate of #59

**Closed by Rmannn** 2020-01-01 03:04 UTC
